---
fixes:
  - |
    apache mod_wsgi does not support passing commandline arguments to the wsgi
    application that it hosts. As a result when the nova api or metadata api
    where run under mod_wsgi it was not possible to use multiple config files
    or non-default file names i.e. nova-api.conf
    This has been addressed by the intoduction of a new, optional, environment
    variable ``OS_NOVA_CONFIG_FILES``. ``OS_NOVA_CONFIG_FILES`` is a ``;``
    separated list of file path relitive to ``OS_NOVA_CONFIG_DIR``.
    When unset the default ``api-paste.ini`` and ``nova.conf`` will be used
    form ``/etc/nova``. This is supported for the nova api and nova metadata
    wsgi applications.

